name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
      - run: echo "Workflow running successfully!"
=======
      - run: echo "Workflow is running successfully!"
>>>>>>> 3bc46198f2fda6ae11750ff9ecc7593fd7eacc39
